const API='https://tyqrkaiwefeogrnyhwin.supabase.co/functions/v1/fsbo-radar';
const NAV=[['dashboard','Dashboard'],['leads','All Leads'],['multi','Multifamily / 2–4'],['rental','Rental SFR'],['ny','New York'],['activity','CRM Activity'],['history','Daily History']];
const state={page:'dashboard',data:null,filters:{q:'',st:'',p:'',d:'',newOnly:false},selected:null,dirty:false};
let auth=sessionStorage.getItem('fsboAuth')||'';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null||v===''?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v));
const num=v=>v==null||v===''?'—':Number(v).toLocaleString();
const date=v=>v?String(v).slice(0,10):'—';
const time=v=>v?new Date(v).toLocaleString():'—';
function toast(t){const n=$('#toast');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1800)}
function sync(kind='ok',txt='Live'){document.querySelectorAll('.dot').forEach(d=>d.className='dot '+(kind==='ok'?'':kind));document.querySelectorAll('.syncTxt').forEach(n=>n.textContent=txt)}
function latestDate(){return state.data?.dailyHistory?.at(-1)?.scan_date?.slice(0,10)||''}
function nav(){const h=NAV.map(([id,l])=>`<button data-page="${id}" class="${state.page===id?'active':''}">${l}</button>`).join('');$('#sideNav').innerHTML=h;$('#mobileNav').innerHTML=h;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page))}
function show(id){state.page=id;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));nav();render()}
function header(t,s){return `<div class="top"><div><h1>${esc(t)}</h1><div class="sub">${esc(s)}</div></div><div class="sync"><i class="dot"></i><span class="syncTxt">Live</span></div></div>`}
async function api(action,opts={}){if(!auth){const e=new Error('Login required');e.status=401;throw e}const u=new URL(API);u.searchParams.set('api',action);if(opts.lead_key)u.searchParams.set('lead_key',opts.lead_key);const f=opts.fetch||{};const h=new Headers(f.headers||{});h.set('authorization',auth);const r=await fetch(u,{...f,headers:h,mode:'cors',cache:'no-store'});const raw=await r.text();let body;try{body=raw?JSON.parse(raw):{}}catch{body={error:raw}}if(!r.ok){const e=new Error(body.error||`HTTP ${r.status}`);e.status=r.status;throw e}return body}
function showLogin(msg=''){const g=$('#authGate');g.classList.remove('hidden');$('#authErr').textContent=msg;$('#authErr').classList.toggle('show',!!msg);setTimeout(()=>$('#authUser').focus(),30)}
function hideLogin(){$('#authGate').classList.add('hidden');$('#authErr').classList.remove('show')}
async function load(silent=false){if(!silent)sync('loading','Syncing…');try{state.data=await api('load');hideLogin();sync('ok','Cloud synced • '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}));render()}catch(e){console.error(e);if(e.status===401){auth='';sessionStorage.removeItem('fsboAuth');sync('error','Sign in required');showLogin('Username or password was not accepted.');return}sync('error','Connection error');if(!silent)$('#dashboard').innerHTML=header('FSBO Opportunity Radar','')+`<div class="notice danger"><b>Cloud CRM connection failed.</b><br>${esc(e.message)}</div>`}}
function counts(){const L=state.data?.leads||[];return{total:L.length,newToday:L.filter(x=>date(x.first_seen)===latestDate()).length,blank:L.filter(x=>!x.disposition).length,called:L.filter(x=>x.disposition==='called').length,working:L.filter(x=>x.disposition==='working').length,converted:L.filter(x=>x.disposition==='converted').length,dead:L.filter(x=>x.disposition==='dead').length}}
function card(label,val,cls='',filter=''){return `<div class="card ${cls}" data-card="${filter}"><div class="label">${label}</div><div class="val">${val}</div></div>`}
function mini(x){return `<div class="leadmini" data-open="${esc(x.lead_key)}"><div class="row"><div><div class="addr">${esc(x.address)}</div><div class="tiny">${esc(x.city)}, ${esc(x.state)} ${esc(x.zip)} • ${esc(x.property_type)}</div></div><div class="money">${money(x.price)}</div></div><div class="tiny" style="margin-top:6px">${esc(x.priority||'')} ${date(x.first_seen)===latestDate()?'<span class="tag new">NEW</span>':''}</div></div>`}
function dashboard(){const c=counts(),L=state.data.leads,H=state.data.dailyHistory,A=state.data.activity||[];const newest=L.filter(x=>date(x.first_seen)===latestDate()).slice(0,12);return header('Opportunity Dashboard','Live FSBO pipeline, daily activity, and follow-up status')+`<div class="cards">${card('New Today',c.newToday,'','new')}${card('Unassigned',c.blank,'','blank')}${card('Called',c.called,'called','called')}${card('Working',c.working,'working','working')}${card('Converted',c.converted,'converted','converted')}${card('Dead',c.dead,'dead','dead')}</div><div class="grid2"><div><div class="panel"><h3>Pipeline</h3><div class="pipeline"><div class="pipe unassigned"><b>${c.blank}</b><span>Unassigned</span></div><div class="pipe called"><b>${c.called}</b><span>Called</span></div><div class="pipe working"><b>${c.working}</b><span>Working</span></div><div class="pipe converted"><b>${c.converted}</b><span>Converted</span></div><div class="pipe dead"><b>${c.dead}</b><span>Dead</span></div></div></div><div class="panel" style="margin-top:14px"><h3>Newest Opportunities</h3><div class="leadcards">${newest.length?newest.map(mini).join(''):'<div class="empty">No new leads in the latest scan.</div>'}</div></div></div><div><div class="panel"><h3>Latest Daily Scan</h3>${H.length?(()=>{const h=H.at(-1);return `<div class="cards" style="grid-template-columns:1fr 1fr;margin:0"><div class="card"><div class="label">Fresh FSBO</div><div class="val">${num(h.fresh_fsbo)}</div></div><div class="card"><div class="label">Investor Pool</div><div class="val">${num(h.investor_pool)}</div></div><div class="card"><div class="label">Multifamily</div><div class="val">${num(h.multifamily)}</div></div><div class="card"><div class="label">Rental SFR</div><div class="val">${num(h.rental_sfr)}</div></div></div>`})():''}</div><div class="panel" style="margin-top:14px"><h3>Recent CRM Activity</h3>${A.slice(0,8).map(a=>`<div class="activityItem" data-open="${esc(a.lead_key)}"><b>${esc(a.address)}</b><div class="tiny">${esc(a.field)}: ${esc(a.old_value||'—')} → ${esc(a.new_value||'—')}</div><div class="tiny">${time(a.created_at)}</div></div>`).join('')||'<div class="empty">No activity yet.</div>'}</div></div></div>`}
function filterBar(base){const states=[...new Set(base.map(x=>x.state).filter(Boolean))].sort();return `<div class="toolbar"><input id="fQ" placeholder="Search address, city, ZIP, notes…" value="${esc(state.filters.q)}"><select id="fSt"><option value="">All states</option>${states.map(s=>`<option ${state.filters.st===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select id="fP"><option value="">All priorities</option><option ${state.filters.p==='Very High'?'selected':''}>Very High</option><option ${state.filters.p==='High'?'selected':''}>High</option></select><select id="fD"><option value="">All statuses</option><option value="blank" ${state.filters.d==='blank'?'selected':''}>Unassigned</option><option value="called" ${state.filters.d==='called'?'selected':''}>Called</option><option value="working" ${state.filters.d==='working'?'selected':''}>Working</option><option value="converted" ${state.filters.d==='converted'?'selected':''}>Converted</option><option value="dead" ${state.filters.d==='dead'?'selected':''}>Dead</option></select><button class="btn ${state.filters.newOnly?'primary':''}" id="fNew">New Today</button></div>`}
function filtered(base){const q=state.filters.q.toLowerCase();return base.filter(x=>{const hay=[x.address,x.city,x.state,x.zip,x.why_flagged,x.dscr_angle,x.notes].join(' ').toLowerCase(),d=x.disposition||'';return(!q||hay.includes(q))&&(!state.filters.st||x.state===state.filters.st)&&(!state.filters.p||x.priority===state.filters.p)&&(!state.filters.d||(state.filters.d==='blank'?!d:d===state.filters.d))&&(!state.filters.newOnly||date(x.first_seen)===latestDate())})}
function table(list){if(!list.length)return'<div class="empty">No leads match these filters.</div>';return `<div class="wrap"><table class="leadtable"><thead><tr><th>Property</th><th>Price</th><th>Type</th><th>Beds/Baths</th><th>Priority</th><th>First Seen</th><th>Status</th><th>Notes</th><th>Zillow</th></tr></thead><tbody>${list.map(x=>`<tr class="${esc(x.disposition||'')}" data-open="${esc(x.lead_key)}"><td><div class="addr">${esc(x.address)}</div><div class="tiny">${esc(x.city)}, ${esc(x.state)} ${esc(x.zip)}</div></td><td class="money">${money(x.price)}</td><td>${esc(x.property_type||'—')}</td><td>${num(x.beds)} / ${num(x.baths)}</td><td><span class="tag ${x.priority==='Very High'?'vh':'high'}">${esc(x.priority||'—')}</span>${date(x.first_seen)===latestDate()?' <span class="tag new">NEW</span>':''}</td><td>${date(x.first_seen)}<div class="tiny">Seen ${num(x.times_seen)}x</div></td><td><select class="statusSel" data-status="${esc(x.lead_key)}"><option value="" ${!x.disposition?'selected':''}>Unassigned</option><option value="called" ${x.disposition==='called'?'selected':''}>Called</option><option value="working" ${x.disposition==='working'?'selected':''}>Working</option><option value="converted" ${x.disposition==='converted'?'selected':''}>Converted</option><option value="dead" ${x.disposition==='dead'?'selected':''}>Dead</option></select></td><td>${esc((x.notes||'').slice(0,70))}${(x.notes||'').length>70?'…':''}</td><td><a class="zlink" href="${esc(x.source_url||'#')}" target="_blank" rel="noopener">Open</a></td></tr>`).join('')}</tbody></table></div>`}
function listPage(title,sub,base){const a=filtered(base);return header(title,sub)+filterBar(base)+`<div class="notice">Showing <b>${a.length}</b> of ${base.length} leads. Click a row to open notes and full history.</div>`+table(a)}
function activity(){const A=state.data.activity||[];return header('CRM Activity','Every saved disposition and note change is timestamped in the shared database')+`<div class="panel">${A.map(a=>`<div class="activityItem" data-open="${esc(a.lead_key)}"><b>${esc(a.address)}</b> <span class="tiny">${esc(a.city)}, ${esc(a.state)}</span><div>${esc(a.field)}: <b>${esc(a.old_value||'—')}</b> → <b>${esc(a.new_value||'—')}</b></div><div class="tiny">${time(a.created_at)}</div></div>`).join('')||'<div class="empty">No CRM activity yet.</div>'}</div>`}
function history(){const H=[...(state.data.dailyHistory||[])].reverse();return header('Daily History','Nationwide fresh-window scan totals')+`<div class="wrap"><table class="leadtable" style="min-width:650px"><thead><tr><th>Date</th><th>Fresh FSBO</th><th>Multifamily</th><th>Rental SFR</th><th>Investor Pool</th></tr></thead><tbody>${H.map(h=>`<tr><td>${date(h.scan_date)}</td><td>${num(h.fresh_fsbo)}</td><td>${num(h.multifamily)}</td><td>${num(h.rental_sfr)}</td><td>${num(h.investor_pool)}</td></tr>`).join('')}</tbody></table></div>`}
function render(){if(!state.data)return;const L=state.data.leads;let html='';if(state.page==='dashboard')html=dashboard();if(state.page==='leads')html=listPage('All Leads','Search and work the cumulative FSBO database',L);if(state.page==='multi')html=listPage('Multifamily / 2–4','High-priority DSCR and refinance opportunities',L.filter(x=>String(x.property_type||'').toLowerCase().includes('multi')));if(state.page==='rental')html=listPage('Rental SFR','Single-family FSBOs captured by rental / tenant language',L.filter(x=>String(x.property_type||'').toLowerCase().includes('single')));if(state.page==='ny')html=listPage('New York','New York investor FSBO opportunities',L.filter(x=>x.state==='NY'));if(state.page==='activity')html=activity();if(state.page==='history')html=history();$('#'+state.page).innerHTML=html;wirePage($('#'+state.page))}
function wirePage(root){root.querySelectorAll('[data-open]').forEach(el=>el.onclick=e=>{if(e.target.closest('a,select,button'))return;openLead(el.dataset.open)});root.querySelectorAll('[data-status]').forEach(s=>s.onchange=e=>{e.stopPropagation();quickStatus(s.dataset.status,s.value)});root.querySelectorAll('[data-card]').forEach(c=>c.onclick=()=>{const v=c.dataset.card;state.filters.newOnly=v==='new';state.filters.d=v==='new'?'':v;show('leads')});const q=root.querySelector('#fQ'),st=root.querySelector('#fSt'),p=root.querySelector('#fP'),d=root.querySelector('#fD'),n=root.querySelector('#fNew');if(q)q.oninput=()=>{state.filters.q=q.value;render()};if(st)st.onchange=()=>{state.filters.st=st.value;render()};if(p)p.onchange=()=>{state.filters.p=p.value;render()};if(d)d.onchange=()=>{state.filters.d=d.value;render()};if(n)n.onclick=()=>{state.filters.newOnly=!state.filters.newOnly;render()}}
async function saveCRM(k,d,n){return api('update',{fetch:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lead_key:k,disposition:d||null,notes:n||''})}})}
async function quickStatus(k,d){const x=state.data.leads.find(v=>v.lead_key===k);if(!x)return;const old=x.disposition;x.disposition=d;render();try{await saveCRM(k,d,x.notes||'');toast('Disposition saved to cloud');await load(true)}catch(e){x.disposition=old;render();toast('Save failed: '+e.message)}}
async function openLead(k){state.selected=k;state.dirty=false;const x=state.data.leads.find(v=>v.lead_key===k);if(!x)return;$('#mAddr').textContent=x.address;$('#mLoc').textContent=`${x.city}, ${x.state} ${x.zip}`;$('#mMetrics').innerHTML=[['Price',money(x.price)],['Beds / Baths',`${num(x.beds)} / ${num(x.baths)}`],['Sq Ft',num(x.sqft)],['Type',x.property_type||'—'],['Priority',x.priority||'—'],['First Seen',date(x.first_seen)],['Last Seen',date(x.last_seen)],['Times Seen',num(x.times_seen)]].map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('');$('#mReason').innerHTML=`<div class="notice"><b>Why flagged:</b> ${esc(x.why_flagged||'—')}<br><b>DSCR / Refi:</b> ${esc(x.dscr_angle||'—')}</div>`;$('#mStatus').value=x.disposition||'';$('#mNotes').value=x.notes||'';$('#mZillow').href=x.source_url||'#';$('#mHistory').innerHTML='<div class="tiny">Loading history…</div>';$('#leadModal').showModal();try{const r=await api('history',{lead_key:k});$('#mHistory').innerHTML='<b>Change History</b>'+((r.history||[]).map(v=>`<div class="histRow"><b>${esc(v.field)}</b>: ${esc(v.old_value||'—')} → ${esc(v.new_value||'—')}<div class="tiny">${time(v.changed_at)}</div></div>`).join('')||'<div class="histRow tiny">No changes yet.</div>')}catch{$('#mHistory').innerHTML='<div class="tiny">Could not load history.</div>'}}
async function saveModal(){const k=state.selected;if(!k)return;const b=$('#mSave');b.disabled=true;b.textContent='Saving…';try{await saveCRM(k,$('#mStatus').value,$('#mNotes').value);toast('Lead saved to cloud');state.dirty=false;await load(true);$('#leadModal').close()}catch(e){toast('Save failed: '+e.message)}finally{b.disabled=false;b.textContent='Save Changes'}}
$('#mClose').onclick=()=>$('#leadModal').close();$('#mSave').onclick=saveModal;$('#mStatus').onchange=()=>state.dirty=true;$('#mNotes').oninput=()=>state.dirty=true;$('#leadModal').addEventListener('cancel',e=>{if(state.dirty&&!confirm('Close without saving your changes?'))e.preventDefault()});
$('#authForm').onsubmit=async e=>{e.preventDefault();const b=$('#authBtn');b.disabled=true;b.textContent='Signing in…';auth='Basic '+btoa(unescape(encodeURIComponent($('#authUser').value.trim()+':'+$('#authPass').value)));sessionStorage.setItem('fsboAuth',auth);try{await load()}finally{b.disabled=false;b.textContent='Open Dashboard'}};
nav();if(auth)load();else showLogin();setInterval(()=>{if(auth&&(!$('#leadModal').open||!state.dirty))load(true)},20000);